/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.parkerbs.Netigate;

import java.io.File;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ryan
 */
public class SettingsGUI extends javax.swing.JFrame {

    /**
     * Creates new form SettingsGUI
     */
    public SettingsGUI() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsPane = new javax.swing.JTabbedPane();
        generalSettingsPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        numberOfBranchesSpinner = new javax.swing.JSpinner();
        generalSettingsSaveButton = new javax.swing.JButton();
        generalSettingsCloseButton = new javax.swing.JButton();
        browseButton = new javax.swing.JButton();
        fileLocationTextBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        customersPerBranchSpinner = new javax.swing.JSpinner();
        emailSettingsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emailSenderTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emailPasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        emailSettingsSaveButton = new javax.swing.JButton();
        emailSettingsClosebutton = new javax.swing.JButton();
        emailToTextField = new javax.swing.JTextField();
        sendEmailCheckBox = new javax.swing.JCheckBox();
        netigateSettingsPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        apiKeyTextBox = new javax.swing.JTextField();
        netigateSettingsSaveButton = new javax.swing.JButton();
        netigateSettingsCloseButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        surveyNumberSpinner = new javax.swing.JSpinner();
        sendToNetigateCheckBox = new javax.swing.JCheckBox();
        activateSurveyCheckBox = new javax.swing.JCheckBox();
        hourComboBox = new javax.swing.JComboBox<>();
        minuteComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        createFilesSettingsPanel = new javax.swing.JPanel();
        createJSONCheckBox = new javax.swing.JCheckBox();
        createCSVCheckBox = new javax.swing.JCheckBox();
        createFilesSaveButton = new javax.swing.JButton();
        createFilesCloseButton = new javax.swing.JButton();
        archiveFilesSettingsPanel = new javax.swing.JPanel();
        archiveFilesSaveButton = new javax.swing.JButton();
        archiveFilesCloseButton = new javax.swing.JButton();
        archiveCSVCheckBox = new javax.swing.JCheckBox();
        archiveJSONCheckBox = new javax.swing.JCheckBox();
        archiveIncomingCheckBox = new javax.swing.JCheckBox();
        archiveLogsCheckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        SQLFilesSaveButton = new javax.swing.JButton();
        SQLFilesCloseButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sqlURLTextField = new javax.swing.JTextField();
        sqlUsernameTextField = new javax.swing.JTextField();
        sqlPasswordField = new javax.swing.JPasswordField();
        sqlUpdateCheckBox = new javax.swing.JCheckBox();
        messagesSettingsPanel = new javax.swing.JPanel();
        messageSettingsSaveButton = new javax.swing.JButton();
        messageSettingsCloseButton = new javax.swing.JButton();
        debugCheckBox = new javax.swing.JCheckBox();
        messageCheckBox = new javax.swing.JCheckBox();
        errorCheckBox = new javax.swing.JCheckBox();
        alertCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        setIconImage(new ImageIcon("C:\\Users\\ryan.clark\\OneDrive - Parker Building Supplies Limited\\Documents\\IT\\Java\\Parker BS.jpg").getImage());

        settingsPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel4.setText("Number of Branches:");

        generalSettingsSaveButton.setText("Save");
        generalSettingsSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalSettingsSaveButtonActionPerformed(evt);
            }
        });

        generalSettingsCloseButton.setText("Close");
        generalSettingsCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalSettingsCloseButtonActionPerformed(evt);
            }
        });

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("File Location:");

        jLabel11.setText("Customers Per Branch:");

        javax.swing.GroupLayout generalSettingsPanelLayout = new javax.swing.GroupLayout(generalSettingsPanel);
        generalSettingsPanel.setLayout(generalSettingsPanelLayout);
        generalSettingsPanelLayout.setHorizontalGroup(generalSettingsPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(generalSettingsPanelLayout.createSequentialGroup().addGap(33, 33, 33)
                        .addGroup(generalSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel4)
                                .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(generalSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                                        .addComponent(numberOfBranchesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(customersPerBranchSpinner, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                60, Short.MAX_VALUE))
                                .addComponent(fileLocationTextBox))
                        .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalSettingsPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(generalSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                        generalSettingsPanelLayout.createSequentialGroup()
                                                .addComponent(generalSettingsSaveButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(generalSettingsCloseButton).addGap(15, 15, 15))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalSettingsPanelLayout
                                        .createSequentialGroup().addComponent(browseButton).addContainerGap()))));
        generalSettingsPanelLayout.setVerticalGroup(generalSettingsPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(generalSettingsPanelLayout.createSequentialGroup().addContainerGap()
                        .addGroup(generalSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(generalSettingsPanelLayout.createSequentialGroup()
                                        .addGroup(generalSettingsPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel4)
                                                .addComponent(numberOfBranchesSpinner,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel11).addComponent(customersPerBranchSpinner,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38))
                                .addGroup(generalSettingsPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7).addComponent(fileLocationTextBox,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(browseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(generalSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(generalSettingsSaveButton).addComponent(generalSettingsCloseButton))
                        .addContainerGap()));

        settingsPane.addTab("General", generalSettingsPanel);

        jLabel1.setText("Email sender:");

        emailSenderTextField.setToolTipText("");

        jLabel2.setText("Password:");

        jLabel3.setText("Email to:");

        emailSettingsSaveButton.setText("Save");
        emailSettingsSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailSettingsSaveButtonActionPerformed(evt);
            }
        });

        emailSettingsClosebutton.setText("Close");
        emailSettingsClosebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailSettingsClosebuttonActionPerformed(evt);
            }
        });

        sendEmailCheckBox.setText("Send Email");
        sendEmailCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sendEmailCheckBoxStateChanged(evt);
            }
        });

        javax.swing.GroupLayout emailSettingsPanelLayout = new javax.swing.GroupLayout(emailSettingsPanel);
        emailSettingsPanel.setLayout(emailSettingsPanelLayout);
        emailSettingsPanelLayout.setHorizontalGroup(emailSettingsPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(emailSettingsPanelLayout.createSequentialGroup().addContainerGap()
                        .addGroup(emailSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(emailSettingsPanelLayout.createSequentialGroup()
                                        .addGroup(emailSettingsPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1).addComponent(jLabel2).addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(emailSettingsPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(emailSenderTextField,
                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(emailPasswordField).addComponent(emailToTextField)))
                                .addGroup(
                                        emailSettingsPanelLayout.createSequentialGroup().addComponent(sendEmailCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        174, Short.MAX_VALUE)
                                                .addComponent(emailSettingsSaveButton).addGap(8, 8, 8)
                                                .addComponent(emailSettingsClosebutton)))
                        .addContainerGap()));
        emailSettingsPanelLayout.setVerticalGroup(emailSettingsPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(emailSettingsPanelLayout.createSequentialGroup().addContainerGap()
                        .addGroup(emailSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
                                .addComponent(emailSenderTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(emailSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
                                .addComponent(emailPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(emailSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel3)
                                .addComponent(emailToTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(emailSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(emailSettingsPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26,
                                                Short.MAX_VALUE)
                                        .addGroup(emailSettingsPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(emailSettingsSaveButton)
                                                .addComponent(emailSettingsClosebutton))
                                        .addContainerGap())
                                .addGroup(emailSettingsPanelLayout.createSequentialGroup().addGap(18, 18, 18)
                                        .addComponent(sendEmailCheckBox)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))));

        settingsPane.addTab("Email", emailSettingsPanel);

        jLabel5.setText("Api Key:");

        netigateSettingsSaveButton.setText("Save");
        netigateSettingsSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netigateSettingsSaveButtonActionPerformed(evt);
            }
        });

        netigateSettingsCloseButton.setText("Close");
        netigateSettingsCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netigateSettingsCloseButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Survey Number:");

        surveyNumberSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(surveyNumberSpinner, "0"));

        sendToNetigateCheckBox.setText("Send To Netigate");
        sendToNetigateCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sendToNetigateCheckBoxStateChanged(evt);
            }
        });

        activateSurveyCheckBox.setText("Activate Survey");

        hourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14",
                        "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        minuteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "15", "30", "45" }));

        jLabel12.setText("Time:");

        javax.swing.GroupLayout netigateSettingsPanelLayout = new javax.swing.GroupLayout(netigateSettingsPanel);
        netigateSettingsPanel.setLayout(netigateSettingsPanelLayout);
        netigateSettingsPanelLayout.setHorizontalGroup(netigateSettingsPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(netigateSettingsPanelLayout.createSequentialGroup().addContainerGap()
                        .addGroup(netigateSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                        netigateSettingsPanelLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE).addComponent(netigateSettingsSaveButton)
                                                .addGap(8, 8, 8).addComponent(netigateSettingsCloseButton))
                                .addGroup(netigateSettingsPanelLayout.createSequentialGroup()
                                        .addGroup(netigateSettingsPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(netigateSettingsPanelLayout.createSequentialGroup()
                                                        .addComponent(sendToNetigateCheckBox).addGap(18, 18, 18)
                                                        .addComponent(activateSurveyCheckBox))
                                                .addGroup(netigateSettingsPanelLayout.createSequentialGroup()
                                                        .addGroup(netigateSettingsPanelLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel6).addComponent(jLabel5))
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(netigateSettingsPanelLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(apiKeyTextBox,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 235,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(netigateSettingsPanelLayout
                                                                        .createSequentialGroup()
                                                                        .addComponent(surveyNumberSpinner,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                90,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(94, 94, 94)
                                                                        .addGroup(netigateSettingsPanelLayout
                                                                                .createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(hourComboBox,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel12))))))
                                        .addGap(18, 18, 18)
                                        .addComponent(minuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 19, Short.MAX_VALUE)))
                        .addContainerGap()));
        netigateSettingsPanelLayout.setVerticalGroup(netigateSettingsPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(netigateSettingsPanelLayout.createSequentialGroup().addContainerGap()
                        .addGroup(netigateSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5)
                                .addComponent(apiKeyTextBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(netigateSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(netigateSettingsPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6).addComponent(surveyNumberSpinner,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(netigateSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sendToNetigateCheckBox).addComponent(activateSurveyCheckBox)
                                .addComponent(hourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(minuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(netigateSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(netigateSettingsSaveButton).addComponent(netigateSettingsCloseButton))
                        .addContainerGap()));

        settingsPane.addTab("Netigate", netigateSettingsPanel);

        createJSONCheckBox.setText("JSON");
        createJSONCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                createJSONCheckBoxStateChanged(evt);
            }
        });

        createCSVCheckBox.setText("CSV");
        createCSVCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                createCSVCheckBoxStateChanged(evt);
            }
        });

        createFilesSaveButton.setText("Save");
        createFilesSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFilesSaveButtonActionPerformed(evt);
            }
        });

        createFilesCloseButton.setText("Close");
        createFilesCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFilesCloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createFilesSettingsPanelLayout = new javax.swing.GroupLayout(createFilesSettingsPanel);
        createFilesSettingsPanel.setLayout(createFilesSettingsPanelLayout);
        createFilesSettingsPanelLayout.setHorizontalGroup(
                createFilesSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(createFilesSettingsPanelLayout.createSequentialGroup().addGap(28, 28, 28)
                                .addGroup(createFilesSettingsPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(createCSVCheckBox).addComponent(createJSONCheckBox))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                createFilesSettingsPanelLayout.createSequentialGroup()
                                        .addContainerGap(261, Short.MAX_VALUE).addComponent(createFilesSaveButton)
                                        .addGap(8, 8, 8).addComponent(createFilesCloseButton).addContainerGap()));
        createFilesSettingsPanelLayout.setVerticalGroup(createFilesSettingsPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(createFilesSettingsPanelLayout.createSequentialGroup().addContainerGap()
                        .addComponent(createCSVCheckBox).addGap(18, 18, 18).addComponent(createJSONCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(createFilesSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(createFilesSaveButton).addComponent(createFilesCloseButton))
                        .addContainerGap()));

        settingsPane.addTab("Create Files", createFilesSettingsPanel);

        archiveFilesSaveButton.setText("Save");
        archiveFilesSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archiveFilesSaveButtonActionPerformed(evt);
            }
        });

        archiveFilesCloseButton.setText("Close");
        archiveFilesCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archiveFilesCloseButtonActionPerformed(evt);
            }
        });

        archiveCSVCheckBox.setText("CSV");

        archiveJSONCheckBox.setText("JSON");

        archiveIncomingCheckBox.setText("Incoming");

        archiveLogsCheckBox.setText("Log");

        javax.swing.GroupLayout archiveFilesSettingsPanelLayout = new javax.swing.GroupLayout(
                archiveFilesSettingsPanel);
        archiveFilesSettingsPanel.setLayout(archiveFilesSettingsPanelLayout);
        archiveFilesSettingsPanelLayout.setHorizontalGroup(
                archiveFilesSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                archiveFilesSettingsPanelLayout.createSequentialGroup()
                                        .addContainerGap(261, Short.MAX_VALUE).addComponent(archiveFilesSaveButton)
                                        .addGap(8, 8, 8).addComponent(archiveFilesCloseButton).addContainerGap())
                        .addGroup(archiveFilesSettingsPanelLayout.createSequentialGroup().addGap(25, 25, 25)
                                .addGroup(archiveFilesSettingsPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(archiveLogsCheckBox).addComponent(archiveIncomingCheckBox)
                                        .addComponent(archiveJSONCheckBox).addComponent(archiveCSVCheckBox))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        archiveFilesSettingsPanelLayout.setVerticalGroup(archiveFilesSettingsPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, archiveFilesSettingsPanelLayout
                        .createSequentialGroup().addContainerGap().addComponent(archiveCSVCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(archiveJSONCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(archiveIncomingCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(archiveLogsCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(archiveFilesSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(archiveFilesSaveButton).addComponent(archiveFilesCloseButton))
                        .addContainerGap()));

        settingsPane.addTab("Archive Files", archiveFilesSettingsPanel);

        SQLFilesSaveButton.setText("Save");
        SQLFilesSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQLFilesSaveButtonActionPerformed(evt);
            }
        });

        SQLFilesCloseButton.setText("Close");
        SQLFilesCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SQLFilesCloseButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("URL:");

        jLabel9.setText("Username:");

        jLabel10.setText("Password");

        sqlUpdateCheckBox.setText("Update Database");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SQLFilesSaveButton).addGap(8, 8, 8).addComponent(SQLFilesCloseButton)
                                .addContainerGap())
                .addGroup(jPanel1Layout.createSequentialGroup().addGap(22, 22, 22).addGroup(jPanel1Layout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(sqlUpdateCheckBox)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel8).addGap(40, 40, 40)
                                        .addComponent(sqlURLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 275,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9).addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(sqlPasswordField).addComponent(sqlUsernameTextField)))))
                        .addContainerGap(65, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sqlURLTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(sqlUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10).addComponent(sqlPasswordField,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sqlUpdateCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SQLFilesSaveButton).addComponent(SQLFilesCloseButton))
                        .addContainerGap()));

        settingsPane.addTab("SQL", jPanel1);

        messageSettingsSaveButton.setText("Save");
        messageSettingsSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageSettingsSaveButtonActionPerfomed(evt);
            }
        });

        messageSettingsCloseButton.setText("Close");
        messageSettingsCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageSettingsCloseButtonActionPerformed(evt);
            }
        });

        debugCheckBox.setText("Debug");

        messageCheckBox.setText("Message");

        alertCheckBox.setText("Alert");

        errorCheckBox.setText("Error");

        javax.swing.GroupLayout messageSettingsPanelLayout = new javax.swing.GroupLayout(messagesSettingsPanel);
        messagesSettingsPanel.setLayout(messageSettingsPanelLayout);
        messageSettingsPanelLayout.setHorizontalGroup(
                messageSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                messageSettingsPanelLayout.createSequentialGroup().addContainerGap(261, Short.MAX_VALUE)
                                        .addComponent(messageSettingsSaveButton).addGap(8, 8, 8)
                                        .addComponent(messageSettingsCloseButton).addContainerGap())
                        .addGroup(messageSettingsPanelLayout.createSequentialGroup().addGap(25, 25, 25)
                                .addGroup(messageSettingsPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(errorCheckBox).addComponent(alertCheckBox)
                                        .addComponent(messageCheckBox).addComponent(debugCheckBox))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        messageSettingsPanelLayout.setVerticalGroup(messageSettingsPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messageSettingsPanelLayout.createSequentialGroup()
                        .addContainerGap().addComponent(debugCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(messageCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alertCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(errorCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(messageSettingsPanelLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(messageSettingsSaveButton).addComponent(messageSettingsCloseButton))
                        .addContainerGap()));

        settingsPane.addTab("Messages", messagesSettingsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(settingsPane));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                settingsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailSettingsClosebuttonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailSettingsClosebuttonActionPerformed
        this.dispose();
    }// GEN-LAST:event_emailSettingsClosebuttonActionPerformed

    private void generalSettingsCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_generalSettingsCloseButtonActionPerformed
        this.dispose();
    }// GEN-LAST:event_generalSettingsCloseButtonActionPerformed

    private void emailSettingsSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailSettingsSaveButtonActionPerformed
        saveSettings();
    }// GEN-LAST:event_emailSettingsSaveButtonActionPerformed

    private void generalSettingsSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_generalSettingsSaveButtonActionPerformed
        saveSettings();
    }// GEN-LAST:event_generalSettingsSaveButtonActionPerformed

    private void netigateSettingsSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_netigateSettingsSaveButtonActionPerformed
        saveSettings();
    }// GEN-LAST:event_netigateSettingsSaveButtonActionPerformed

    private void netigateSettingsCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_netigateSettingsCloseButtonActionPerformed
        this.dispose();
    }// GEN-LAST:event_netigateSettingsCloseButtonActionPerformed

    private void createFilesSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createFilesSaveButtonActionPerformed
        saveSettings();
    }// GEN-LAST:event_createFilesSaveButtonActionPerformed

    private void createFilesCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createFilesCloseButtonActionPerformed
        this.dispose();
    }// GEN-LAST:event_createFilesCloseButtonActionPerformed

    private void archiveFilesSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_archiveFilesSaveButtonActionPerformed
        saveSettings();
    }// GEN-LAST:event_archiveFilesSaveButtonActionPerformed

    private void archiveFilesCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_archiveFilesCloseButtonActionPerformed
        this.dispose();
    }// GEN-LAST:event_archiveFilesCloseButtonActionPerformed

    private void createCSVCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_createCSVCheckBoxStateChanged
        archiveCSVCheckBox.setEnabled(createCSVCheckBox.isSelected());

        if (!createCSVCheckBox.isSelected()) {
            archiveCSVCheckBox.setSelected(false);
        }
    }// GEN-LAST:event_createCSVCheckBoxStateChanged

    private void createJSONCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_createJSONCheckBoxStateChanged
        archiveJSONCheckBox.setEnabled(createJSONCheckBox.isSelected());

        if (!createJSONCheckBox.isSelected()) {
            archiveJSONCheckBox.setSelected(false);
        }
    }// GEN-LAST:event_createJSONCheckBoxStateChanged

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setCurrentDirectory(new File(ConfigFile.getFileLocation()));
        int returnValue = chooser.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            fileLocationTextBox.setText(chooser.getSelectedFile().getPath());
        }
    }// GEN-LAST:event_browseButtonActionPerformed

    private void SQLFilesSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SQLFilesSaveButtonActionPerformed
        saveSettings();
    }// GEN-LAST:event_SQLFilesSaveButtonActionPerformed

    private void SQLFilesCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SQLFilesCloseButtonActionPerformed
        this.dispose();
    }// GEN-LAST:event_SQLFilesCloseButtonActionPerformed

    private void sendEmailCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_sendEmailCheckBoxStateChanged
        emailSenderTextField.setEnabled(sendEmailCheckBox.isSelected());
        emailPasswordField.setEnabled(sendEmailCheckBox.isSelected());
        emailToTextField.setEnabled(sendEmailCheckBox.isSelected());
    }// GEN-LAST:event_sendEmailCheckBoxStateChanged

    private void sendToNetigateCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_sendToNetigateCheckBoxStateChanged
        activateSurveyCheckBox.setEnabled(sendToNetigateCheckBox.isSelected());
        if (!sendToNetigateCheckBox.isSelected()) {
            activateSurveyCheckBox.setSelected(false);
        }
    }// GEN-LAST:event_sendToNetigateCheckBoxStateChanged

    private void messageSettingsSaveButtonActionPerfomed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SQLFilesSaveButtonActionPerformed
        saveSettings();
    }

    private void messageSettingsCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SQLFilesCloseButtonActionPerformed
        this.dispose();
    }//

    /**
     * @param args the command line arguments
     */
    /* Create and display the form */
    /*
     * java.awt.EventQueue.invokeLater(new Runnable() { public void run() { new
     * SettingsGUI().setVisible(true); } });
     */

    public void setSQLUpdate(Boolean status) {
        sqlUpdateCheckBox.setSelected(status);
    }

    public Boolean getSQLUpdate() {
        return sqlUpdateCheckBox.isSelected();
    }

    public void setDebug(Boolean status) {
        debugCheckBox.setSelected(status);
    }

    public Boolean getDebug() {
        return debugCheckBox.isSelected();
    }

    public void setError(Boolean status) {
        errorCheckBox.setSelected(status);
    }

    public Boolean getError() {
        return errorCheckBox.isSelected();
    }

    public void setAlert(Boolean status) {
        alertCheckBox.setSelected(status);
    }

    public Boolean getAlert() {
        return alertCheckBox.isSelected();
    }

    public void setMessage(Boolean status) {
        messageCheckBox.setSelected(status);
    }

    public Boolean getMessage() {
        return messageCheckBox.isSelected();
    }

    public void setHour(String hour) {
        hourComboBox.setSelectedItem(hour);
    }

    public void setMinute(String minute) {
        minuteComboBox.setSelectedItem(minute);
    }

    public void setActivateSurvey(Boolean status) {
        activateSurveyCheckBox.setSelected(status);
    }

    public void setSendToNetigate(Boolean status) {
        sendToNetigateCheckBox.setSelected(status);
    }

    public void setCustomersPerBranch(int customers) {
        customersPerBranchSpinner.setValue(customers);
    }

    public void setSendEmail(Boolean status) {
        sendEmailCheckBox.setSelected(status);
    }

    public void setSQLURL(String url) {
        sqlURLTextField.setText(url);
    }

    public void setSQLUsername(String username) {
        sqlUsernameTextField.setText(username);
    }

    public void setSQLPassword(String password) {
        sqlPasswordField.setText(password);
    }

    public void setFileLocation(String path) {
        fileLocationTextBox.setText(path);
    }

    public void setArchiveCSV(Boolean status) {
        archiveCSVCheckBox.setSelected(status);
    }

    public void setArchiveJSON(Boolean status) {
        archiveJSONCheckBox.setSelected(status);
    }

    public void setArchiveIncoming(Boolean status) {
        archiveIncomingCheckBox.setSelected(status);
    }

    public void setArchiveLogs(Boolean status) {
        archiveLogsCheckBox.setSelected(status);
    }

    public void setCreateCSV(Boolean status) {
        createCSVCheckBox.setSelected(status);
    }

    public void setCreateJSON(Boolean status) {
        createJSONCheckBox.setSelected(status);
    }

    public void setSurveyNumber(int surveyNumber) {
        surveyNumberSpinner.setValue(surveyNumber);
    }

    public int getSurveyNumber() {
        return (int) surveyNumberSpinner.getValue();
    }

    public void setNumberOfBranches(int numberOfBranches) {
        numberOfBranchesSpinner.setValue(numberOfBranches);
    }

    public int getNumberOfBranches() {
        return (Integer) numberOfBranchesSpinner.getValue();
    }

    public void setEmailSenderTextField(String emailSender) {
        emailSenderTextField.setText(emailSender);
    }

    public String getEmailSenderTextField() {
        return emailSenderTextField.getText();
    }

    public void setEmailSendToTextField(String emailTo) {
        emailToTextField.setText(emailTo);
    }

    public String getEmailSendToTextField() {
        return emailToTextField.getText();
    }

    public String getPassword() {
        return String.valueOf(emailPasswordField.getPassword());
    }

    public void setPassword(String password) {
        emailPasswordField.setText(password);
    }

    public void setApiKey(String apiKey) {
        apiKeyTextBox.setText(apiKey);
    }

    public void saveSettings() {
        try {
            new InternetAddress(emailToTextField.getText()).validate();
            new InternetAddress(emailSenderTextField.getText()).validate();

            ConfigFile.setNumberOfBranches((int) numberOfBranchesSpinner.getValue());
            ConfigFile.setCustomersPerBranch((int) customersPerBranchSpinner.getValue());
            ConfigFile.setFileLocation(fileLocationTextBox.getText());
            ConfigFile.setSendEmail(sendEmailCheckBox.isSelected());
            ConfigFile.setSender(emailSenderTextField.getText());
            ConfigFile.setPassword(String.valueOf(emailPasswordField.getPassword()));
            ConfigFile.setSendTo(emailToTextField.getText());
            ConfigFile.setApiKey(apiKeyTextBox.getText());
            ConfigFile.setSurveyNumber((int) surveyNumberSpinner.getValue());
            ConfigFile.setSendToNetigate(sendToNetigateCheckBox.isSelected());
            ConfigFile.setActivateSurvey(activateSurveyCheckBox.isSelected());
            ConfigFile.setHour(String.valueOf(hourComboBox.getSelectedItem()));
            ConfigFile.setMinute(String.valueOf(minuteComboBox.getSelectedItem()));
            ConfigFile.setCreateCSV(createCSVCheckBox.isSelected());
            ConfigFile.setCreateJSON(createJSONCheckBox.isSelected());
            ConfigFile.setArchiveCSV(archiveCSVCheckBox.isSelected());
            ConfigFile.setArchiveJSON(archiveJSONCheckBox.isSelected());
            ConfigFile.setArchiveIncoming(archiveIncomingCheckBox.isSelected());
            ConfigFile.setArchiveLogs(archiveLogsCheckBox.isSelected());
            ConfigFile.setSqlURL(sqlURLTextField.getText());
            ConfigFile.setSqlusername(sqlUsernameTextField.getText());
            ConfigFile.setSqlpassword(String.valueOf(sqlPasswordField.getPassword()));
            ConfigFile.setSQLUpdate(sqlUpdateCheckBox.isSelected());
            ConfigFile.setDebug(debugCheckBox.isSelected());
            ConfigFile.setError(errorCheckBox.isSelected());
            ConfigFile.setMessage(messageCheckBox.isSelected());
            ConfigFile.setAlert(alertCheckBox.isSelected());

            ConfigFile.writeConfig();
        } catch (AddressException ex) {
            JOptionPane.showMessageDialog(rootPane, ex, "Email Address Invalid", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SQLFilesCloseButton;
    private javax.swing.JButton SQLFilesSaveButton;
    private javax.swing.JCheckBox activateSurveyCheckBox;
    private javax.swing.JTextField apiKeyTextBox;
    private javax.swing.JCheckBox archiveCSVCheckBox;
    private javax.swing.JButton archiveFilesCloseButton;
    private javax.swing.JButton archiveFilesSaveButton;
    private javax.swing.JPanel archiveFilesSettingsPanel;
    private javax.swing.JCheckBox archiveIncomingCheckBox;
    private javax.swing.JCheckBox archiveJSONCheckBox;
    private javax.swing.JCheckBox archiveLogsCheckBox;
    private javax.swing.JButton browseButton;
    private javax.swing.JCheckBox createCSVCheckBox;
    private javax.swing.JButton createFilesCloseButton;
    private javax.swing.JButton createFilesSaveButton;
    private javax.swing.JPanel createFilesSettingsPanel;
    private javax.swing.JCheckBox createJSONCheckBox;
    private javax.swing.JSpinner customersPerBranchSpinner;
    private javax.swing.JPasswordField emailPasswordField;
    private javax.swing.JTextField emailSenderTextField;
    private javax.swing.JButton emailSettingsClosebutton;
    private javax.swing.JPanel emailSettingsPanel;
    private javax.swing.JButton emailSettingsSaveButton;
    private javax.swing.JTextField emailToTextField;
    private javax.swing.JTextField fileLocationTextBox;
    private javax.swing.JButton generalSettingsCloseButton;
    private javax.swing.JPanel generalSettingsPanel;
    private javax.swing.JButton generalSettingsSaveButton;
    private javax.swing.JComboBox<String> hourComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel messagesSettingsPanel;
    private javax.swing.JButton messageSettingsSaveButton;
    private javax.swing.JButton messageSettingsCloseButton;
    private javax.swing.JCheckBox debugCheckBox;
    private javax.swing.JCheckBox alertCheckBox;
    private javax.swing.JCheckBox messageCheckBox;
    private javax.swing.JCheckBox errorCheckBox;
    private javax.swing.JCheckBox sqlUpdateCheckBox;
    private javax.swing.JComboBox<String> minuteComboBox;
    private javax.swing.JButton netigateSettingsCloseButton;
    private javax.swing.JPanel netigateSettingsPanel;
    private javax.swing.JButton netigateSettingsSaveButton;
    public static javax.swing.JSpinner numberOfBranchesSpinner;
    private javax.swing.JCheckBox sendEmailCheckBox;
    private javax.swing.JCheckBox sendToNetigateCheckBox;
    private javax.swing.JTabbedPane settingsPane;
    private javax.swing.JPasswordField sqlPasswordField;
    private javax.swing.JTextField sqlURLTextField;
    private javax.swing.JTextField sqlUsernameTextField;
    private javax.swing.JSpinner surveyNumberSpinner;
    // End of variables declaration//GEN-END:variables
}
